version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=example_crud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432